### ISSUE TITLE
Using tabs

### ISSUE THREAD

**Issue by admojica** [PSPDFKit/Cordova-iOS#20]
I am trying to open multiple PDF files in different tabs as you can see here: https://pspdfkit.com/blog/2015/pspdfkit-ios-5-0/ but i cannot find the method to do that, can you tell me how can i do that with your plugin? Thanks

**Comment by steipete** [comment]
That's https://pspdfkit.com/api/ios/Classes/PSPDFTabbedViewController.html - this is not something we expose in Cordova, but since it's open source you can use it just as in all the samples we provide in PSPDFCatalog and build your own API around it.

If you have detail questions please ping us with a runnable sample at https://pspdfkit.com/support/request

We can't write that wrapper part for you for free, but paid development services are also possible. Let us know how we can help best on our support portal.
