### ISSUE TITLE
Adding right button items renders in reverse order

### ISSUE THREAD

**Issue by twinj** [PSPDFKit/Cordova-iOS#34]
PSPDFKitPlugin.setRightBarButtonItems(['annotation', 'bookmark', 'brightness']);

The screen will show the right buttons in the reverse order.

When using setLeft the order is correct.

**Comment by steviki** [comment]
This is actually the expected behavior, as this is how UIKit handles bar button items.

Please see the `UINavigationItem` documentation for further explanation:
https://developer.apple.com/documentation/uikit/uinavigationitem/1624956-rightbarbuttonitems
https://developer.apple.com/documentation/uikit/uinavigationitem/1624946-leftbarbuttonitems

`rightBarButtonItems`:
> Items are displayed right-to-left in the same order as they appear in the array. 

`leftBarButtonItems`:
> Items are displayed left-to-right in the same order as they appear in the array.

**Comment by twinj** [comment]
Ahh ok. Thanks for pointing that out.
