### ISSUE TITLE
Request: Ability to import / export annotations as JSON

### ISSUE THREAD

**Issue by greggarson** [PSPDFKit/Cordova-iOS#57]
It appears based on this article https://pspdfkit.com/guides/ios/current/annotations/exportingimporting-tofrom-json/ that this can already be done at the iOS level.  Any thoughts on exposing this functionality through the Cordova wrapper?

**Comment by steipete** [comment]
Hi Greg!

We're in the process of deprecating the old iOS JSON export/import, because it's hard to use on other platforms and was created before PSPDFKit expanded to Android, macOS, Web and Windows.

Our best answer for syncing annotations is our Instant SDK: https://pspdfkit.com/instant/

We also opened up the data format Instant uses under the hood:
https://pspdfkit.com/guides/ios/current/importing-exporting/instant-json/

Depending on your use case, you could also use XFDF. 

What company do you represent, and do you have a license yet? This allows us to better schedule potential future improvements to the wrapper. Of course, if you want to take up the wrapping on your own, we also accept Pull Requests once a CLA is signed (and we'll also help you out if you get stuck somewhere - the iOS API is pretty straightforward so it wouldn't be too hard.)
