### ISSUE TITLE
Get all FormFields

### ISSUE THREAD

**Issue by KatGr** [PSPDFKit/Cordova-iOS#81]
Hello, 
I am so glad that it is finally possible to prefill formFields.
I just have one problem:
We have different templates with different formFields. If I try to fill an unknown formField I get an info/error popup from pspdfkit, which is bad.
So is there a way to get all available formField-Names or a way to suppress the popup (ignoring  non existing fieldNames)?

**Comment by radazzouz** [comment]
@KatGr,

Thanks for writing in!

I will address your questions inline below:

> We have different templates with different formFields. If I try to fill an unknown formField I get an info/error popup from pspdfkit.

When we fail to fill a form field you send an error over. If you prefer to silently fail instead of showing the error, you can remove the `sendPluginResult` in the `else` or use `CDVCommandStatus_OK` instead of `CDVCommandStatus_ERROR`. 

https://github.com/PSPDFKit/Cordova-iOS/blob/847bca817c15af54bc25987810a93d26ec15d441/PSPDFKitPlugin/PSPDFKitPlugin.m#L1664-L1669

For more details, please take a look at our knowledge base article here: https://pspdfkit.com/guides/ios/current/knowledge-base/what-is-the-correct-way-to-handle-an-error-in-javaScript-in-cordova/

> So is there a way to get all available formField-Names

You can use `getAnnotations()` and pass the desired page index and `widget` for the annotation type, to get the forms at a given page, then you can extract the value of `formFieldName`:

```js
PSPDFKitPlugin.getAnnotations(pageIndex, 'widget', function(forms) {
	if (forms) {
		alert("Forms for page at index " + pageIndex + ": " + JSON.stringify(forms));
	}
});
```
Note that the value of forms is in Instant JSON format, for more details, please take a look at our documentation here: https://pspdfkit.com/guides/ios/current/importing-exporting/instant-json/

I am closing this issue, but please do not hesitate to reach out to us in our support portal at https://support.pspdfkit.com/hc/en-us/requests/new should you have any further questions.

Once again, thank you!
